package org.example.orm;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
public @interface ColumnInfo {
    String name();
    boolean autoGenerated() default false;

    String cast() default "";
}
