package org.danilkha.entities;

import org.example.orm.ColumnInfo;
import org.example.orm.Entity;

import java.util.Date;
import java.util.UUID;

@Entity(tableName = "email_confirmation_codes")
public record ConfirmationCodeEntity(
        @ColumnInfo(name = "account_id") UUID userId,
        @ColumnInfo(name = "code") int code,
        @ColumnInfo(name = "creation_time", autoGenerated = true) Date creationTime
) {
}
