package org.danilkha.entities;

import org.example.orm.ColumnInfo;
import org.example.orm.Entity;

import java.util.UUID;

@Entity(tableName = "topic")
public record TopicEntity (
        @ColumnInfo(name = "id", autoGenerated = true) UUID id,
        @ColumnInfo(name = "name") String name,
        @ColumnInfo(name = "picture") String picture
){

}
