package org.danilkha.entities;

import org.danilkha.dto.UserDto;
import org.danilkha.entities.typeconverters.UUIDTypeConverter;
import org.example.orm.ColumnInfo;
import org.example.orm.Entity;
import org.example.orm.TypeConverters;

import java.util.UUID;

@Entity(tableName = "account")
public record UserEntity(
        @TypeConverters(typeConverterClass = UUIDTypeConverter.class)
        @ColumnInfo(name = "id", autoGenerated = true)
        UUID id,
        @ColumnInfo(name = "password_hash") String encodedPasswordHash,
        @ColumnInfo(name = "email") String email,
        @ColumnInfo(name = "username") String userName,
        @ColumnInfo(name = "avatar_uri") String avatarUri,
        @ColumnInfo(name = "is_email_confirmed") boolean isEmailConfirmed
) {

    public UserDto toDto(){
        return new UserDto(
                id,
                userName,
                email,
                avatarUri,
                isEmailConfirmed
        );
    }
}
