package org.danilkha.entities;

import org.danilkha.dto.UserDto;
import org.example.orm.ColumnInfo;
import org.example.orm.Entity;
import org.jetbrains.annotations.Nullable;

import java.util.UUID;

@Entity(tableName = "account")
public record UserEntity(
        @ColumnInfo(name = "id", autoGenerated = true)
        UUID id,
        @ColumnInfo(name = "password_hash") String encodedPasswordHash,
        @ColumnInfo(name = "email") String email,
        @ColumnInfo(name = "username") String username,
        @ColumnInfo(name = "name") String firstname,
        @ColumnInfo(name = "surname") String surname,
        @ColumnInfo(name = "avatar_uri") String avatarUri,
        @ColumnInfo(name = "is_email_confirmed") boolean isEmailConfirmed
) {

    public UserDto toDto(){
        return new UserDto(
                id,
                username,
                firstname,
                surname,
                email,
                avatarUri,
                isEmailConfirmed
        );
    }
}
