package org.danilkha.entities;

import org.danilkha.dto.UserDto;
import org.danilkha.entities.typeconverters.DateTypeConverter;
import org.example.orm.ColumnInfo;
import org.example.orm.Entity;
import org.example.orm.TypeConverters;

import java.util.Date;
import java.util.UUID;

@Entity(tableName = "account")
public record UserEntity(
        @ColumnInfo(name = "id", autoGenerated = true) UUID id,
        @ColumnInfo(name = "password_hash") String encodedPasswordHash,
        @ColumnInfo(name = "email") String email,
        @ColumnInfo(name = "username") String username,
        @ColumnInfo(name = "name") String firstname,
        @ColumnInfo(name = "surname") String surname,
        @ColumnInfo(name = "avatar_uri") String avatarUri,
        @ColumnInfo(name = "registration_date", cast = "date")
        @TypeConverters(typeConverterClass = DateTypeConverter.class)
        Date registrationDate
) {

    public UserDto toDto(String basePicturePath){
        return new UserDto(
                id,
                username,
                firstname,
                surname,
                email,
                encodedPasswordHash,
                basePicturePath+"/"+avatarUri,
                registrationDate
        );
    }
}
